create table choices (id int4 generated by default as identity, name varchar(50) not null, question_id int4, primary key (id));
create table questions (id int4 generated by default as identity, question_type varchar(13) not null, title varchar(50) not null,favorite boolean, primary key (id));
create table survey_contrains_question (survey_id int4 not null, question_id int4 not null, primary key (survey_id, question_id));
create table surveys (id int4 generated by default as identity, title varchar(50) not null, primary key (id));
alter table if exists choices add constraint FK4vhssp102sjhbey1y4rhiiyos foreign key (question_id) references questions;
alter table if exists survey_contains_question add constraint FKa3ibbrtlt4qv35d2p2aniq1so foreign key (question_id) references questions;
alter table if exists survey_contains_question add constraint FK1jcju9aq1x88set020tdkru22 foreign key (survey_id) references surveys;